version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # For development you can mount the code:
    # volumes:
    #   - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_frontend
    ports:
      - "3000:80"   # host:container (access frontend at http://localhost:3000)
    depends_on:
      - backend
