name: AI Fraud Detection CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------------- Python (Backend) ----------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true   # don't fail if file is empty

      - name: Run Python lint
        run: |
          cd backend
          pip install flake8
          flake8 . || true   # allow warnings, don't stop workflow

      # ---------------- Node.js (Frontend) ----------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build || echo "Skipping build (no script found)"
